### PR TITLE
Allow to disable Entrez search result limit

### LINKED ISSUE #16: Entrez search result limit
Hello! 
I've come to this project since the BioPython entrez search fail me.
It used to return more than 9999 results but now there's this cursed limit.
so several question
1. Is the default search the same as the one in BioPython?
2. Are the articles added by relevancy?  In BioPython they are, and the first articles MIDs here and there are different
3. And most important one, how can I get more then 9999 results? I've tried the 'in_batchs_of' with the entrez_api.search function but I still get only 9999 results

I need the most simple use of these functions, I want to put a term ('T cell' for example) and get a list of the most 100k relevant articles PMIDs. That's the only thing standing in my project way

Cheers

### PR DESCRIPTION
**Pull request by jonasfreimuth**
Fixes the limit on `max_results` for `EntrezAPI.search()` and adds an option to ignore all similar limits.

Should pretty much close #16, at least for my purposes.

Note: Running `pytest` on commit [3c2b396](https://github.com/krassowski/easy-entrez/pull/18/commits/3c2b39663fd5882880f7625db47316ae68c2cc7c) resulted in the following output once, but the error disappeared after I ran it again without changing anything, the programmers ~dream~ nightmare.

```
(.venv) jfreige@sl-akali-p-cs1:easy-entrez (16-entrez-result-limit)$ pytest
============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.12, pytest-7.4.2, pluggy-1.3.0
rootdir: /data/local/jfreige/geo-mining/easy-entrez
plugins: cov-4.1.0
collected 15 items                                                                                                                                                                                               

tests/test_api.py ..F                                                                                                                                                                                      [ 20%]
tests/test_parsing.py ....                                                                                                                                                                                 [ 46%]
tests/test_queries.py ........                                                                                                                                                                             [100%]

==================================================================================================== FAILURES ====================================================================================================
___________________________________________________________________________________________________ test_fetch ___________________________________________________________________________________________________

    def test_fetch():
        result = entrez_api.fetch(['4'], max_results=1, database='snp')
        assert is_response_for(result, FetchQuery)
        assert not is_response_for(result, SearchQuery)
        snp = result.data[0]
        namespaces = {'ns0': 'https://www.ncbi.nlm.nih.gov/SNP/docsum'}
>       chromosome = snp.find('.//ns0:CHR', namespaces).text
E       AttributeError: 'NoneType' object has no attribute 'text'

tests/test_api.py:38: AttributeError
================================================================================================ warnings summary ================================================================================================
tests/test_parsing.py:39
  /data/local/jfreige/geo-mining/easy-entrez/tests/test_parsing.py:39: PytestUnknownMarkWarning: Unknown pytest.mark.optional - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.optional

tests/test_parsing.py:78
  /data/local/jfreige/geo-mining/easy-entrez/tests/test_parsing.py:78: PytestUnknownMarkWarning: Unknown pytest.mark.optional - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.optional

tests/test_parsing.py:89
  /data/local/jfreige/geo-mining/easy-entrez/tests/test_parsing.py:89: PytestUnknownMarkWarning: Unknown pytest.mark.optional - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.optional

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================ short test summary info =============================================================================================
FAILED tests/test_api.py::test_fetch - AttributeError: 'NoneType' object has no attribute 'text'
==================================================================================== 1 failed, 14 passed, 3 warnings in 4.47s ====================================================================================```

### CODE REVIEW

**Comment by jonasfreimuth** [comment]
Ok hold on while I sign my commits...

**Comment by jonasfreimuth** [comment]
Also, yes, I've noticed the error above is different to the one mentioned in #19, and will be looking into if this is a problem.

**Comment by jonasfreimuth** [comment]
I don't think the readthedocs fail has anything to do with this PR, right?

**Comment by krassowski** [comment]
Hi @jonasfreimuth thank you for this!

Can you please merge with the main branch which now includes a fix for the docs (#20) so that we can see if they build properly?

**Comment by jonasfreimuth** [comment]
Will do, hang on.

**Comment by jonasfreimuth** [comment]
Ok it's merged. @krassowski you might have to manually allow the other checks to run again...

**Review by krassowski — APPROVED** [review]
Thank you @jonasfreimuth

**Pull request merged**
